//! Parity test harness — loads golden fixtures generated by Python and
//! compares Rust output against them.
//!
//! Fixtures are JSON files under `rust_port/fixtures/`.
//!
//! ## Float comparison
//!
//! - Prices (entry, exit, TP, SL): epsilon = 1e-10
//! - Percentages (PnL, win_rate, drawdown): epsilon = 1e-6
//! - NaN positions must match exactly.

use claude_trader_models::{
    Candle, ExitReason, MarketType, PositionType, ResolutionLevel, Signal, EPSILON_PCT,
    EPSILON_PRICE,
};
use std::path::{Path, PathBuf};

/// Root directory for golden fixtures.
fn fixtures_dir() -> PathBuf {
    // CARGO_MANIFEST_DIR points to crates/models/; fixtures are at rust_port/fixtures/
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("fixtures")
}

/// Assert two f64 values are within epsilon, with context on failure.
fn assert_approx_eq(actual: f64, expected: f64, epsilon: f64, context: &str) {
    if expected.is_nan() {
        assert!(actual.is_nan(), "{context}: expected NaN, got {actual}");
        return;
    }
    if expected.is_infinite() {
        assert!(
            actual.is_infinite() && actual.signum() == expected.signum(),
            "{context}: expected {expected}, got {actual}"
        );
        return;
    }
    let diff = (actual - expected).abs();
    assert!(
        diff <= epsilon,
        "{context}: expected {expected}, got {actual} (diff={diff}, epsilon={epsilon})"
    );
}

/// Assert two price values match within price epsilon.
fn assert_price_eq(actual: f64, expected: f64, context: &str) {
    assert_approx_eq(actual, expected, EPSILON_PRICE, context);
}

/// Assert two percentage values match within percentage epsilon.
fn assert_pct_eq(actual: f64, expected: f64, context: &str) {
    assert_approx_eq(actual, expected, EPSILON_PCT, context);
}

// ---------------------------------------------------------------------------
// Smoke tests — fixture directory and model round-trips
// ---------------------------------------------------------------------------

#[test]
fn test_fixtures_dir_exists() {
    let dir = fixtures_dir();
    assert!(
        dir.exists(),
        "Fixtures directory does not exist: {}",
        dir.display()
    );
}

#[test]
fn test_signal_roundtrip() {
    let signal = Signal {
        signal_date: chrono::Utc::now(),
        position_type: PositionType::Long,
        ticker: "BTCUSDT".to_string(),
        pattern: "test".to_string(),
        tp_pct: Some(3.0),
        sl_pct: Some(1.5),
        tp_price: None,
        sl_price: None,
        leverage: 5.0,
        market_type: MarketType::Futures,
        taker_fee_rate: 0.0005,
        entry_price: None,
        fill_timeout_seconds: 3600,
        entry_delay_seconds: None,
        max_holding_hours: 72,
        size_multiplier: 1.0,
        metadata: Default::default(),
    };

    let json = serde_json::to_string(&signal).unwrap();
    let recovered: Signal = serde_json::from_str(&json).unwrap();

    assert_eq!(recovered.ticker, "BTCUSDT");
    assert_eq!(recovered.position_type, PositionType::Long);
    assert_price_eq(recovered.leverage, 5.0, "leverage");
    assert_pct_eq(recovered.tp_pct.unwrap(), 3.0, "tp_pct");
    assert_pct_eq(recovered.sl_pct.unwrap(), 1.5, "sl_pct");
}

#[test]
fn test_candle_roundtrip() {
    let candle = Candle {
        open_time: chrono::Utc::now(),
        close_time: chrono::Utc::now(),
        open: 50000.0,
        high: 51000.0,
        low: 49000.0,
        close: 50500.0,
        volume: 1234.56,
        taker_buy_volume: 600.0,
    };

    let json = serde_json::to_string(&candle).unwrap();
    let recovered: Candle = serde_json::from_str(&json).unwrap();

    assert_price_eq(recovered.open, 50000.0, "open");
    assert_price_eq(recovered.close, 50500.0, "close");
}

#[test]
fn test_enum_serialization() {
    assert_eq!(
        serde_json::to_string(&PositionType::Long).unwrap(),
        "\"LONG\""
    );
    assert_eq!(
        serde_json::to_string(&PositionType::Short).unwrap(),
        "\"SHORT\""
    );
    assert_eq!(serde_json::to_string(&ExitReason::Tp).unwrap(), "\"TP\"");
    assert_eq!(
        serde_json::to_string(&ResolutionLevel::Hour).unwrap(),
        "\"1h\""
    );
    assert_eq!(
        serde_json::to_string(&ResolutionLevel::Minute).unwrap(),
        "\"1m\""
    );
    assert_eq!(
        serde_json::to_string(&ResolutionLevel::Trade).unwrap(),
        "\"trade\""
    );
}
